spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:credit_application_system_db
    username: cami
    password:


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false